apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: monitor-release
spec:
  workspaces:
    - name: output
  params:
    - description: Release to monitor
      name: release
      type: string
  steps:
    - name: monitor-release
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/output/source
      script: |
        STATUS=$(oc get -f "$(params.release)" -o jsonpath='{.status.conditions[?(@.type=="Released")].status}')
        if [ "$STATUS" = "False" ]; then
          echo "Release has failed. Exiting."
          oc get -f "$(params.release)" -o yaml
          exit 1
        fi

        echo "Waiting for Released=True..."
        oc wait --for=condition=Released -f "$(params.release)" --timeout=$(params.wait-timeout)

        echo "Waiting for Validated=True..."
        oc wait --for=condition=Validated -f "$(params.release)" --timeout=$(params.wait-timeout)

        echo "Release is both Released and Validated."
