apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: monitor-release
spec:
  workspaces:
    - name: output
  params:
    - description: Release to monitor
      name: release
      type: string
  steps:
    - name: monitor-release
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/output/source
      script: |
        # Check the release status
        STATUS=$(oc get -f "$(params.release)" -o jsonpath='{.status.conditions[?(@.type=="Released")].status}')
        if [ "$STATUS" = "False" ]; then
          echo "Release has failed. Exiting."
          exit 0 #tmp as I want it to pass needs to be removed
        fi

        # Wait for Released=True
        oc wait --for=condition=Released -f "$(params.release)" --timeout=1h

        # Wait for Validated=True
        oc wait --for=condition=Validated -f "$(params.release)" --timeout=1h
