apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: apply-manifests
spec:
  workspaces:
    - name: output
  stepTemplate:
    env:
      - name: HOME
        value: /workspace
    image: quay.io/konflux-ci/appstudio-utils:48c311af02858e2422d6229600e9959e496ddef1@sha256:91ddd999271f65d8ec8487b10f3dd378f81aa894e11b9af4d10639fd52bba7e8
  params:
    - description: Manifest to apply
      name: manifest
      type: string
  steps:
    - name: apply-manifest
      workingDir: /workspace/output/source
      script: |
        echo "Applying: $(params.manifest)"
        oc apply -f "$(params.manifest)"
