apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/JasonPowr/konflux-staging-test?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
    pipelinesascode.tekton.dev/pipeline: ".tekton/staging-pipeline.yaml"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: konflux-staging-test
    appstudio.openshift.io/component: konflux-staging-test
    pipelines.appstudio.openshift.io/type: build
  name: konflux-staging-test-on-push
  namespace: japower-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: releases
    value: |
      - type: component
        run: true
        releasePlanDir: v1.0/component/releasePlans
        releaseDir: v1.0/component/releases
  pipelineRef:
    name: rhtas-release
  taskRunTemplate:
    serviceAccountName: rhtas-staging-sa
  taskRunSpecs:
    - pipelineTaskName: clone-repository
      serviceAccountName: appstudio-pipeline
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
