apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/JasonPowr/konflux-staging-test?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
    pipelinesascode.tekton.dev/pipeline: ".tekton/staging-pipeline.yaml"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: konflux-staging-test
    appstudio.openshift.io/component: konflux-staging-test
    pipelines.appstudio.openshift.io/type: build
  name: konflux-staging-test-on-push
  namespace: japower-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: component-release-plan-dir
    value: 'v1.0/component/releasePlans'
  - name: component-release-dir
    value: 'v1.0/component/releases'
  - name: fbc-release-plan-dir
    value: 'v1.0/fbc/releasePlans'
  - name: fbc-release-dir
    value: 'v1.0/fbc/releases'
  pipelineRef:
    name: rhtas-release
  taskRunSpecs:
    - pipelineTaskName: apply-component-release-plans
      serviceAccountName: rhtas-staging-sa
    - pipelineTaskName: apply-component-release
      serviceAccountName: rhtas-staging-sa
    - pipelineTaskName: monitor-component-release
      serviceAccountName: rhtas-staging-sa
    - pipelineTaskName: apply-fbc-release-plans
      serviceAccountName: rhtas-staging-sa
    - pipelineTaskName: apply-fbc-release
      serviceAccountName: rhtas-staging-sa
    - pipelineTaskName: monitor-fbc-release
      serviceAccountName: rhtas-staging-sa
    - pipelineTaskName: process-releases
      serviceAccountName: rhtas-staging-sa
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
